# ---------------------------------------------------------------
# ---------------------------------------------------------------
#  配置文件 大纲
#  基本配置  *********
#  head.ejs   头部     |  header.ejs 导航栏
#  sidebar.ejs侧边栏   |  unit.ejs 新增无影响其他功能插件
#  footer.ejs jio部   |  index.ejs 主题排版  
#  post.ejs   文章页   |  第三方插件配置，如需开启 ：true
#  *.ejs 其他功能 推出中...
#
#  links.ejs\Permalinks.ejs\axis.ejs
#  Permalinks：友情链接模板\永久链接模板\时间轴
#
#  第三方插件/功能
#  \  pjax、外部链接拦截提示、搜索、调试、评论、自定义文章悬浮颜色
#  \  自定义音乐播放、背景效果、观察者模式、离线访问功能
#  \  自定义设置画布(canvas)、 主题颜色配置、 置顶功能
#     
# ---------------------------------------------------------------
# ---------------------------------------------------------------

# 涉及的 文章内容 一些设置

# 可设置置顶功能，文章作者，首页展示的图片，分类，标签 设置如下
# 在文章markdown添加 
# topping: true      # 将最近的几篇文章中置顶 
# author: 测试小刘~   # 设置文章作者
# img: /zw.jpg       # 首页展示的图片 #前提是启用主题的图文排版
# categories         # 分类
# tags               # 标签


# 例如以下为文章markdown:
# ---
# title: markdown 如何编写文章.md
# date: 10:41 2019/11/25
# topping: true
# author: 测试小明~
# img: https://img.xjh.me/desktop/bg/nature/65231080_p0.jpg
# categories:
# - 博客
# tags:
# - hexo
# ---

# Markdown 的使用和快捷键方法.
# 吧啦吧啦 ....
#  <!--more-->  # 这个意思是以上都为概述，以下内容在首页不展示。具体看官方文档
#  <!-- toc -->  # 产生目录

# 内容......




# 详细介绍没有在文档中介绍 https://github.com/ZHD99/hexo-theme-dearmsdan
# 但是你可以提交文档

# ---------------------------------------------------------------
#  基本配置  *********
# ---------------------------------------------------------------

sitename: hi mogul # 网站名字
sitekeywords: hi mogul,hexo-theme-dearmsdan一款Hexo主题宝钻蓝色,It gives people a sense of emptiness,hexo简约主题,HEXO,dearmsdan.com # 网站关键词
sitedescription: It gives people a sense of emptiness  # 网站描述


# ---------------------------------------------------------------
#  head.ejs  全局样式 引用的样式和插件
# ---------------------------------------------------------------

# 网站小图标
favicon: 
  href: /logo.png # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)
  
# 阿里 图标库 
aliiconfont: //at.alicdn.com/t/font_1605171_5fpik914nu9.css

# jq库
jquery:
  js: #https://libs.baidu.com/jquery/2.1.4/jquery.min.js 
    one: /js/jquery1.10.2.min.js
    two: https://libs.baidu.com/jquery/2.1.4/jquery.min.js 
# bootstrap
bootstrap:
  css: /css/bootstrap-3.3.4.css
  js: /js/bootstrap-3.3.4.js
# 头像 css 把这删除头像就不动了
title_qiaoba: /css/avatar_user.css
# slimscroll 滚动条
slimscroll: /js/jquery.slimscroll.min.js
# dearmsdan-post-Statistics样式
Statistics: /css/post_content.css
# dearmsdan-post-Statistics样式
social:
  css: /css/social/social.css
  fontcss: /css/social/waesome.css
nav:
  css: /css/navEffect.css
# 网站加载条
loadingBar:
  pace: /resources/loadingBar/pace.min.js
  pink: /resources/loadingBar/flash.css
  band: /js/headBand.min.js
  #pace: https://cdn.bootcss.com/pace/1.0.2/pace.min.js
  #pink: https://cdn.bootcss.com/pace/1.0.2/themes/pink/pace-theme-flash.css
# pjax配置
jquerypjax:
  pjax: /js/pjax/jquery.pjax.js
toc:
  css: /resources/toc/toc.css
  pageslide: /resources/toc/jquery.pageslide.js
#  复制功能插件
copycode: 
  lib: /js/copycode/clipboard.min.js


# ---------------------------------------------------------------
#  header.ejs 导航栏
# ---------------------------------------------------------------


dearmsdan:
  logo:  #logo图标设置（设置其中之一就好了
    ico: DearMsDanIconFont icon-zh    #这里将logo设置 图标库ICO
    png: 						      #这里将logo设置图片
    size: 50px # 设置logo大小
  title: 
    size: 20px # 设置网站名字大小

# 顶部菜单
menu:
  首页:
    - /
  关于:
    - about.html
  留言板:
    - /valine.html
  友情链接:
    - /link.html
  
  
# ---------------------------------------------------------------
#  sidebar.ejs 侧边栏
# ---------------------------------------------------------------


# 样式在source/css/avatar_user.css 中 5行 左右
# 设置图片不动的配置在 title_qiaoba 中
# 填写一个即可，另一个备用(第二个有抖动特效)   任意一个都可以为空
# 尽可能选择正比例图片！！！，比例差距大可以修改 ejs 模板源文件 sidebar.ejs 5~ 10行左右
dearHead: /Pexels.gif # 初始头像
dearHeadlogo: /logo.png # 遮罩 logo
PhotoHead: /resources/qiaoba.png  # 备用头像 


# 社交按钮配置
socialbtn:
  GitHub:
    - https://github.com/ZHD99/
    - icon-git
  email:
    - mailto:dearmsdan@outlook.com
    - icon-youxiang
  netease:
    - https://music.163.com/
    - icon-netease
  qq:
    - https://wpa.qq.com/msgrd?v=3&uin=2646405301&site=qq&menu=yes
    - icon-qq
  weibo:
    - https://weibo.com/
    - icon-weibo
	
# 可自定义一级或者二级目录，按照以下规则添加
# cataTarget跳转方式，在当前页跳转 或 重新打开一页，可参看HTML a标签，target属性
cataTarget: _self # 当前 _self 重新打开_blank 
Catalog:
  目录1:
    搜索: 
      - https://www.baidu.com/
    email:
      - mailto:dearmsdan@outlook.com
    404:
      - /about3.html
	
	
# 统计
count:
  articles: 文章
  tags: 标签
  categories: 分类

# 文章类
side:
  archive: 文章归档
  recent_posts: 最新文章
  categories: 文章分类
  tagcloud: 标签 
  axis: 
    name: 时间轴
    link: /axis.html
    
  
# 文章迭代
sides:  
- category #文章分类
- tagcloud #标签
- archive #文章归档
- recent_posts #最新文章



# ---------------------------------------------------------------
#  unit.ejs 
# ---------------------------------------------------------------

# 音乐播放器
player:
  audio:
    css: /resources/meuplayer/css/player.css
    js: 
      index: /resources/meuplayer/player/index.js
      player: /resources/meuplayer/player/player.js
      playlist: /resources/meuplayer/player/playlist.js
	  
# 返回顶部
top:     #  爱心状: love 箭头: arrow 三角形：triangle   
  clip: arrow   # 具体更改在 ../layout/_plug/top.ejs

# ---------------------------------------------------------------
#  footer.ejs  底部部的配置
# ---------------------------------------------------------------


# footer 时间统计
jscex:
  jsq: /resources/jscex/jscex.min.js             # 必须
  jsa: /resources/jscex/jscex-parser.js          # 必须
  jsz: /resources/jscex/jscex-jit.js             # 必须
  jsw: /resources/jscex/jscex-builderbase.min.js # 必须
  jss: /resources/jscex/jscex-async.min.js       # 必须
  jsx: /resources/jscex/jscex-async-powerpack.min.js

# footer 版权和一些信息
footer:
  # text 和 beian 信息都可以删除或者修改
  text: ""
  
  beian: "<a style='color:#939393;' href='http://hn.beian.miit.gov.cn/' target='_blank'> <img width='16px' src='https://img.alicdn.com/tfs/TB1..50QpXXXXX7XpXXXXXXXXXX-40-40.png' />湘ICP备20001824号 </a>·<a target='_blank' href='http://www.beian.gov.cn/portal/registerSystemInfo' style='display:inline-block;text-decoration:none;height:20px;line-height:20px;'><p style='height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;'>湘公网安备 43010302001049号</p></a>"

# footer 页jio的时间
# 时间年月日，注意月份是0-11 !!
  time: 
    year: 2019
    m: 11
    d: 25



# ---------------------------------------------------------------
#  post.ejs 
# ---------------------------------------------------------------

# 可将文章设置为其他作者，在文章markdown添加
# author: dearmsdan  就可以设置为其他作者

# 页脚  版权设置
copyright:
  author: 本文作者
  permalink: 本文链接
  author_: '德阿姆斯丹 · 迪尔斯'  # 默认作者
  permalink_: https://www.dearmsdan.com/ # 可不填, 自动设置为您的 config(site) 设置


# ---------------------------------------------------------------
#  Permalinks
# ---------------------------------------------------------------

# 友情链接 配置信息
link:
  css: /resources/dearmsdan_link/link.css
  
  
links: 		 # 被遍历的所有网站信息

#***** 以下为示例模板，具体参考文档
  百度...:  # 友情链接的名字
    img: /logo.png   # 友情链接的图片
    link: https://www.baidu.com/ # 网址
    description: "全球最大的中文搜索引擎、致力于让网民更便捷地获取信息，找到所求。百度超过千亿的中文网页数据库，可以瞬间找到相关的搜索结果。"  # 描述
  腾讯...:
    img: /logo.png
    link: https://www.tencent.com/
    description: "腾讯于1998年11月成立，是一家以互联网为基础的平台公司，通过技术丰富互联网用户的生活，助力企业数字化升级。我们的使命是“用户为本 科技向善"


# ---------------------------------------------------------------
#  app.ejs/pjax.ejs  主题排版 
# ---------------------------------------------------------------

# 默认为空  为空标识默认排版
# 默认排版：default   
# 图文排列：textarrement  
# 如果有好看且有趣的排版建议可联系我添加

opPost: "0.5" # 文章内容悬浮 透明度设置
typesetting:
  type: 'default'   # 为空代表默认排版 default、textarrement

# 默认排版设置 move(上移)、jump (空跳)、stick（便利贴）
textdefault: 
  type: 'stick' # 选取默认排列的类型
  opi: "0.4"    # 默认排版 首页文章列表的 透明度设置
  opih: "0.3"   # 默认排版 文章列表悬浮 透明度设置
  
  
# 图文排版设置 S、M、L  小、中、大码
textarrement:
  type: '' # 选取图文排列的类型
  S: 
    color: # 小图片排版 留白的颜色设置
      pc0: # rgb(255, 255, 255)  # 示例注释,不喜欢都可以注释
      pc1: rgb(255, 255, 255)    # 示例颜色 白
      pc2: rgb(63, 63, 63)       # 示例颜色 灰
      pc3: rgb(255, 103, 103)    # 示例颜色 虹
      pc4: rgb(255, 85, 164)     # 示例颜色 粉
      pc5: rgb(191, 0, 255)      # 示例颜色 紫
      pc6: rgb(0, 20, 255)       # 示例颜色 靛
      pc7: rgb(0, 162, 255)      # 示例颜色 蓝
      pc8: rgb(0, 255, 78)       # 示例颜色 绿
      pc9: rgb(255, 226, 0)      # 示例颜色 黄
      pc10: rgb(255, 128, 0)     # 示例颜色 橙
      pc11: rgb(255, 0, 0)       # 示例颜色 红
  M:  
    imgProportion: 1 # 填写 图片比例  1~10   （flex）
    contextProportion: 3 # 填写 文字比例  1~10  （flex）
  
# 图片颜色深？ 试试降低透明度
    sop: 0.8 # S排版 文章列表透明度 值为 0.01 ~ 1 
# 图片排版 背景遮罩透明度设置
  opacity: '0.5' # 值为 0.01 ~ 1 
  
# opacity 在S排版时设置0.1 ，sop 设置0.9以下 有颜色效果




# ---------------------------------------------------------------
#  主题颜色配置  节日主题、自定义画布会覆盖此配置
# ---------------------------------------------------------------

# 可填 rgb、rgba、hs....
dearmsdanColorConfig:
  enable: f  # 填true开启,填f关闭  主题颜色配置！！！ 默认关闭
  a:                  # 超链接 和 一些悬事件
  navbar:             # 导航栏颜色
  sidebar:            # 侧边栏
  sidebarbox:         # 侧边栏 阴影
  bg:                 # 中间透明的颜色
  nav:      #一级导航 颜色配置
    bg:               # 一级导航 背景颜色
    border:           # 一级导航 一边颜色
  nav2:    # 二级级导航 颜色配置
    bg:               # 二级导航 背景颜色
    hover:            # 二级导航 颜色




# ---------------------------------------------------------------
#  画布diy canvas  配置信息
# ---------------------------------------------------------------

# 好看是用性能换的
# 自定义画布 (只有少女系移动端可查看，暂未测试
#   彩系=> 无情纸屑: confetti 纯白球: funPure
# 少女系=> 悬浮心: floatheart 旋转心: whirling 错乱心: seeding
meCanvas:  # 填以上 例如: floatheart

dearmsdandate: /js/diy/date.js
canvas:
  particleCanvas: /js/diy/particleCanvas.js  # TGideas团队编写的粒子类动画组件
  season: # 四季变化小图片
    enable: true # 填true开启,填f关闭 四季变化小图片, 不喜欢，怕消耗性能可以关闭
    img1: /resources/season/flake.png
    img2: /resources/season/watermelon.png
    img3: /resources/season/butterfly.png
    img4: /resources/season/snowflake.png
# 四季变化配置 
seasonimg1: #  1~3 月份 春
  number: 5 # 释放的数量
  op: # 透明度
    min: 1   # 最小值 min max speed 均可为小数类型
    max: 1   # 最大值
  size: # 大小
    min: 40  # 最小值
    max: 60  # 最大值
  zoom: # 缩放(我也不知道有没有用)
    min: 1   # 最小值
    max: 1   # 最大值
  speed: # 移动速度
    min: 1   # 最小值
    max: 3   # 最大值
  angle: # 移动角度
    value: 150 # 角度 向左
    float: 50  # 试试就知道了，大概是偏移量
  rota:
    value: 30   # 旋转值
    speed: 1.6  # 旋转速度
	
seasonimg2: #  3~6 月份 夏
  number: 8 # 释放的数量
  op: # 透明度
    min: 0.4   # 最小值 min max speed 均可为小数类型
    max: 1   # 最大值
  size: # 大小
    min: 30  # 最小值
    max: 60  # 最大值
  zoom: # 缩放(我也不知道有没有用)
    min: 1   # 最小值
    max: 1   # 最大值
  speed: # 移动速度
    min: 2   # 最小值
    max: 5   # 最大值
  angle: # 移动角度
    value: 150 # 角度 向左
    float: 50  # 试试就知道了，大概是偏移量
  rota:
    value: 30   # 旋转值
    speed: 0.8  # 旋转速度	
	
seasonimg3: #  6~9 月份 秋
  number: 30 # 释放的数量
  op: # 透明度
    min: 0.5   # 最小值 min max speed 均可为小数类型
    max: 1   # 最大值
  size: # 大小
    min: 8  # 最小值
    max: 22  # 最大值
  zoom: # 缩放(我也不知道有没有用)
    min: 1   # 最小值
    max: 1   # 最大值
  speed: # 移动速度
    min: 1   # 最小值
    max: 2   # 最大值
  angle: # 移动角度
    value: 150 # 角度 向左
    float: 50  # 试试就知道了，大概是偏移量
  rota:
    value: 30   # 旋转值
    speed: 1.6  # 旋转速度
	
seasonimg4: #  9~12 月份 冬
  number: 50 # 释放的数量
  op: # 透明度
    min: 0.1   # 最小值 min max speed 均可为小数类型
    max: 1   # 最大值
  size: # 大小
    min: 20  # 最小值
    max: 60  # 最大值
  zoom: # 缩放(我也不知道有没有用)
    min: 1   # 最小值
    max: 1   # 最大值
  speed: # 移动速度
    min: 1   # 最小值
    max: 3   # 最大值
  angle: # 移动角度
    value: 150 # 角度 向左
    float: 50  # 试试就知道了，大概是偏移量
  rota:
    value: 30   # 旋转值
    speed: 1.6  # 旋转速度






# ---------------------------------------------------------------
#  第三方插件 | 均为关闭状态 
# ---------------------------------------------------------------

# 外部链接拦截提示
# 可填写正则表达式
# 暂提供2条安全链接
linker:  # 默认关闭， 随意关闭开启
  enable: true # 填true开启,填f关闭 
  site: http.+zhd99.cn 
  sitee: http.+dearmsdan
# 如果不懂，那直接就把dearmsdan，换成自己的网站
# 如：你的网站是www.baidu.com , 示例:http.+baidu （不带域名)
# 意思是文章链接网址 http到dearmsdan 的格式链接不拦截 
  link: /links.html # 默认link: /links.html
# 拦截跳转的链接文件位置在 dearmsdan/source/links.html
# http://link.dearmsdan.com/links.html



# 悬浮文章上变色功能，可能需要进入post文章页显示效果
# 喜欢什么颜色都可以添加，色调要相似网页才能美观，以下提供示例颜色~
dearmsdanPostColor: 
  pc0: # 0 4px 24px rgb(255, 255, 255) # 示例注释,不喜欢都可以注释
  pc1: 0 4px 24px rgb(255, 255, 255) # 示例颜色 白
  pc2: 0 4px 24px rgb(163, 163, 163) # 示例颜色 灰
  pc3: 0 4px 24px rgb(206, 154, 154) # 示例颜色 虹
  pc4: 0 4px 24px rgb(206, 154, 178) # 示例颜色 粉
  pc5: 0 4px 24px rgb(193, 154, 206) # 示例颜色 紫
  pc6: 0 4px 24px rgb(154, 158, 206) # 示例颜色 靛
  pc7: 0 4px 24px rgb(154, 187, 206) # 示例颜色 蓝
  pc8: 0 4px 24px rgb(154, 206, 170) # 示例颜色 绿
  pc9: 0 4px 24px rgb(206, 200, 154) # 示例颜色 黄
  pc10: 0 4px 24px rgb(206, 180, 154) # 示例颜色 橙
  pc11: 0 4px 24px rgb(206, 154, 154) # 示例颜色 红




# 搜索插件
# 请安装 ↓ 插件才能使用全文搜索, 
# npm install hexo-generator-search  --save
# npm install hexo-generator-searchdb --save
# 然后在全局 config 设置 ↓ 如果不懂（https://github.com/theme-next/hexo-generator-search）
# search:
# path: search.xml

search:
  enable: true # 填true开启,填f关闭， 默认不启用，没安装插件启用 会报错
  searchjs: /js/s.js
# ***注意，搜索也会有出错的时候，比如文章中的非法字符会导致搜索功能失效，与本主题无关
# ***需要自己在localhost:4000/search.xml 索引寻找非法字符 在md编辑器删除就正常了


# 调试功能 
eruda:
  enable: f # 填true开启,填f关闭 ， 默认不启用，无需安装插件，开启即可
  init: eruda.init(); # 初始化
  js: //cdn.jsdelivr.net/npm/eruda # js
  
 
 # 离线访问
 # 顾名思义，只要在有网络的地方访问一次即可实现离线访问，将数据存储在本地的意思，提高用户体验
 # 注意事项：
 # 如果开启，修改主题源码或者配置文件都不会生效，需要清除缓存
 # sw由于无法直接访问浏览器相关的API 需要在主题目录下./dearmsdan/source 找到 sw-cache.js 文件
 # 第一行，更改 var version = "v1"; version的值，最好是英文，然后过段时间自动更新缓存！
 # 如果想立即生效的话，通过 右击检查(DevTools开发者工具), 找到Application(存储)->Clear storage(缓存存储)，都删除就生效了
 # 注意！！！！如果想使用离线访问，但怕麻烦忽略以上操作，使用以下步骤
 
 # 只要是开启过 需要清除缓存 Clear storage(缓存存储)
 # 1、在更改主题或者更改的过程中关闭离线访问enable: f 
 # 2、如果修改完之后想要发布的时候(hexo d) 在主题目录下./dearmsdan/source 找到 sw-cache.js 文件 第一行，更改 var version = "v1"; 
 # 3、version的v1 每次需要与上一次不一样就可以了
 #    例如：第一次发布改为是v1,第二次v2,但不能是v1,如果第二次与第一次相同，将无法给用户更新版本
 # 4、开启离线访问  enable: true
servicework:
  enable: f # 填true开启,填f关闭


# pjax 顾名思义 无刷新网页跳转 ( 影响收录
pjax:         
  enable: true # 填true开启,填f关闭 , 默认开启
  

# valine 评论插件  如果有好的评论插件可以，用issues 方式推荐给我哦~
# 使用方法 https://valine.js.org/quickstart.html
valine: 
  enable: true # 填true开启,填f关闭  文章评论
  js: /js/valine.js
  appId: jNrzXxvqR3NhebnE7swyQBFp-gzGzoHsz
  appKey: iqXsTlkThMqeaKdhYcgajztG
  avatar: robohash
  placeholder: 留下你的小脚印吧~
  
# https://img.xjh.me/random_img.php?type=bg&ctype=nature&return=302
# https://img.xjh.me/random_img.php?type=bg&amp;ctype=nature&amp;return=302
# http://vjs.zencdn.net/v/oceans.webm
# 背景效果设置 
# 背景效果均为随机
# 背景可设置为 默认图片() 图片特效(img)、视频(video)

background:     
# 背景图片设置
  bg: '' # 默认背景 和 默认文章图片
  op: '0.3' # 背景透明度  0.1~1
  verification: 'img'  # 参数: 默认为空是关闭、img、video
  imgapi:  # 图片地址 或者图片api   这三个图片地址 verification 为img 的时候轮播的图片
    img1: 'https://api.vvhan.com/api/view' 
    img2: 'https://api.vvhan.com/api/acgimg'
    img3: 'https://api.pingping6.com/tools/acg3/index.php'
    img4: 'http://api.mtyqx.cn/api/random.php'
  video:   # 视频地址 可自定义格式!每次网页刷新，视频随机
# 仿以下格式 可自定义无数个随机背景视频，且不重复即可
    video1: # 计算原因，video1 出现频率为2/100，其他均为随机1/100
      src: '/dearmsdan/video/IronMan.mp4' # 视频类型默认为mp4
      type: "video/mp4"  # 视频类型
    video2: 
      src: 'http://vjs.zencdn.net/v/oceans.webm' # 视频类型默认为webm
      type: "video/webm"  # 视频类型
    video3: 
      src: '/dearmsdan/video/IronMan2.mp4' 
      type: "video/mp4"  # 视频类型
  opacity: '0.2'   # 设置视频/图片背景透明度 0.1~1
# opacity:0.2
  videoMax: '768'   # 默认 768  
# 屏幕宽度小于videoMax数值 将背景视频停止播放
  bcopacity: '0.5'  # 0.1~1
# 移动端背景底部颜色透明度 ！！！ 如果移动端不喜欢透明度设置为1
  staticopacity: '0.8'  # 0.1~1
# 移动端背景底部修饰颜色透明度




# 自定义音乐
#  示例音乐均来自猪厂，artist：作者、poster：歌曲小图片、MP3：音乐格式支持(webmv, ogv, m4v, oga, mp3等等) 

playervolume: 14        # 默认音量 80    值为  0~100
playerloop: true        # 默认循环播放： true  不循环播放： false 
playerpautoPlay: true   # 默认自动播放： true  不自动播放： false 
playerlsit:
  Right Here Waiting:
    artist: Richard Marx
    mp3: http://music.163.com/song/media/outer/url?id=3313653.mp3
    poster: http://p2.music.126.net/_62h3kA2WCrYEXWL0yaJ7Q==/1743825441658717.jpg?param=130y130
  勇气:
    artist: 棉子
    mp3: http://music.163.com/song/media/outer/url?id=1411358329.mp3
    poster: http://p2.music.126.net/QcWNRX_0uhckImvF2nN1xA==/109951164573973377.jpg?param=130y130
  东京不太热:
    artist: 封茗囧菌
    mp3: http://music.163.com/song/media/outer/url?id=34723470.mp3
    poster: http://p1.music.126.net/srjmIxgdjRlCXSjZtl2aaw==/109951163825045428.jpg?param=90y90
  空山新雨后:
    artist: 冷十三
    mp3: http://music.163.com/song/media/outer/url?id=1397565121.mp3
    poster: http://p1.music.126.net/jio03zzjVqkuofI0054Syg==/109951164433163481.jpg?param=177y177
  拜拜:
    artist: 小竖琴
    mp3: http://music.163.com/song/media/outer/url?id=1383594415.mp3
    poster: http://p1.music.126.net/aRpHnChT3GFQI7AsqCw6iA==/109951164284919406.jpg?param=130y130
  冬眠:
    artist: 司南
    mp3: http://music.163.com/song/media/outer/url?id=1398663411.mp3
    poster: http://p1.music.126.net/4KDBaQXnQywQovmqvjx-8Q==/109951164444131697.jpg?param=130y130
  我的名字:
    artist: 焦迈奇
    mp3: http://music.163.com/song/media/outer/url?id=554241732.mp3
    poster: http://p1.music.126.net/a_rb8pgC5R_hO-lfm7acSw==/109951164019567772.jpg?param=130y130
  还是分开:
    artist: 张叶蕾
    mp3: http://music.163.com/song/media/outer/url?id=465921195.mp3
    poster: http://p1.music.126.net/tH5FdakJX47uy8mlM0GMWQ==/19218363741925314.jpg?param=130y130
  云烟成雨:
    artist: 房东的猫
    mp3: http://music.163.com/song/media/outer/url?id=513360721.mp3
    poster: http://p1.music.126.net/DSTg1dR7yKsyGq4IK3NL8A==/109951163046050093.jpg?param=130y130
	
	
	
	
AboutMe: '德阿姆斯丹 · 迪尔斯'
	
	

# 仿以下格式 可自定义无数个随机背景视频，且不重复即可
#    video1: # 计算原因，video1 出现频率为2/100，其他均为随机1/100
#      src: '/dearmsdan/video/IronMan.mp4' # 视频类型默认为mp4
#      type: "video/mp4"  # 视频类型
#    video2: 
#      src: '/dearmsdan/video/oceans.webm' # 视频类型默认为webm
#      type: "video/webm"  # 视频类型
#    video3: 
#      src: '/dearmsdan/video/IronMan2.mp4' 
#      type: "video/mp4"  # 视频类型
#    video4: 
#      src: '/dearmsdan/video/IronMan3.mp4' 
#      type: "video/mp4"  # 视频类型
#    video5: 
#      src: '/dearmsdan/video/IronMan4.mp4' 
#      type: "video/mp4"  # 视频类型
#    video6: 
#      src: '/dearmsdan/video/thor.mp4' 
#      type: "video/mp4"  # 视频类型
#    video7: 
#      src: '/dearmsdan/video/Strange.mp4' 
#      type: "video/mp4"  # 视频类型
#    video8: 
#      src: '/dearmsdan/video/Marvel.mp4' 
#      type: "video/mp4"  # 视频类型